rocketmq:
  producer:
    endpoints: 172.16.2.252:8081
  push-consumer:
    endpoints: 172.16.2.252:8081

spring:
  application:
    name: mikeiansky-for-spring-boot-mq
  rocketmq:
    consumer:
      #group: springboot3_consumer_group
      # ????????????????????????????
      pull-batch-size: 10
    name-server: 172.16.2.252:9876
    producer:
      # ??????????????group?????
      group: springboot3_producer_group
      # ???????????3000
      sendMessageTimeout: 10000
      # ?????????????2
      retryTimesWhenSendFailed: 2
      # ???????????2
      retryTimesWhenSendAsyncFailed: 2
      # ?????????1024 * 1024 * 4(??4M)
      maxMessageSize: 4096
      # ?????????4k(1024 * 4)
      compressMessageBodyThreshold: 4096
      # ???????????????broker???false
      retryNextServer: false